[package]
name = "Lugli-language-compiler"
version = "0.1.0"
description = "My 'lugli' language compiler created by me"
authors = ["Vinicios Lugli <vinicioslugli@gmail.com>"]
edition = "2018"

[dependencies]
logos = "0.12.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
# panic = "abort"